version: 2.1

orbs:
  win: circleci/windows@4.1.1

commands:
  ulimit:
    parameters:
      n: { type: integer }
    steps:
    - run:
        command: "echo 'ulimit -n <<parameters.n>>' >> $BASH_ENV"

  concat_packages:
    description: >-
      Collect the names and versions of packages used in the csproj file,
      and concatenate them to create a checksum for NuGet package caching.
    parameters:
      output_path: { type: string }
    steps:
      - run:
          name: Concatenate the names and versions of packages
          command: |
            dotnet msbuild -t:ListPackageReference -nologo \
            | sort \
            | uniq \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/  //' > <<parameters.output_path>>
            cat <<parameters.output_path>>
          shell: bash

  codecov:
    description: Upload a code coverage report file to Codecov.io
    parameters:
      file: { type: string }
    steps:
    - restore_cache:
        keys:
        - "v1-codecov"
    - run:
        name: Upload a code coverage report file to Codecov.io
        shell: bash
        command: |
          set -evx
          case "$OSTYPE" in
            darwin*) plat=macos;;
            msys*)   plat=windows; suffix=.exe;;
            cygwin*) plat=windows; suffix=.exe;;
            *)       plat=linux;;
          esac
          mkdir -p _codecov_uploader/$plat/
          pushd _codecov_uploader/$plat/
          if [[ ! -f "codecov$suffix" ]]; then
            curl -OL "https://uploader.codecov.io/latest/$plat/codecov$suffix"
          fi
          chmod +x "codecov$suffix"
          popd
          "_codecov_uploader/$plat/codecov$suffix" \
            -K \
            -f '<<parameters.file>>' \
            -n "$CIRCLE_BUILD_NUM"
        when: always
    - save_cache:
        key: "v1-codecov"
        paths:
        - _codecov_uploader/
        when: always

  netcore_build_base:
    parameters:
      test_filter:
        type: string
        default: ""
    steps:
    - checkout
    - concat_packages:
        output_path: .package-references.txt
    - restore_cache:
        keys:
        - v1-deps-{{ arch }}-{{ checksum ".package-references.txt" }}
        - v1-deps-{{ arch }}
    - run: dotnet restore
    - save_cache:
        key: v1-deps-{{ arch }}-{{ checksum ".package-references.txt" }}
        paths:
        - "{{}}"
    - run: dotnet build --no-restore -c Release -p:SkipSonar=true
    - run: echo "<<parameters.test_filter>>" > .test_filter.txt
    - persist_to_workspace:
        root: .
        paths:
        - .test_filter.txt
        - "*/bin/"
        - "*/obj/"

  netcore_test_base:
    parameters:
      test_filter:
        type: string
        default: ""
      locale:
        type: string
        default: en_US.UTF-8
      code_coverage:
        type: boolean
        default: true
    steps:
    - when:
        condition: "<<parameters.code_coverage>>"
        steps:
        - restore_cache:
            keys:
            - v1-dotcover-{{ arch }}
        - run:
            name: Install JetBrains dotCover
            command: >-
              dotnet tool install
              --global
              JetBrains.dotCover.GlobalTool
              --version 2021.2.2
        - save_cache:
            key: v1-dotcover-{{ arch }}
            paths:
            - ~/.nuget/packages
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Distribute tests
        shell: pwsh
        command: |
          $testFilter = "<<parameters.test_filter>>"
          $filter = if ($testFilter) {
              $testFilter
          } else {
              Get-Content -Path .test_filter.txt -ErrorAction SilentlyContinue
          }
          $seed = $(git rev-parse HEAD).GetHashCode()
          $items = dotnet test `
              --configuration Release `
              --no-restore --no-build `
              --nologo `
              --list-tests `
              --filter $filter
          $items = $items | Where-Object {
              $_ -match "    "
          } | ForEach-Object {
              $_ -replace "^    (.+?)(\(.+\))?`$", "`$1"
          } | Select-Object -Unique
          $items = $items | Get-Random -SetSeed $seed -Count $items.Length
          $nodeIndex = [int]$env:CIRCLE_NODE_INDEX
          $nodeCount = [int]$env:CIRCLE_NODE_TOTAL
          $part = [int][Math]::Ceiling($items.Length / $nodeCount)
          $tests = $items[($nodeIndex * $part)..(($nodeIndex + 1) * $part - 1)]
          Set-Content -Path ".test_filter.txt" -Value $($tests -join "|")
          Write-Host $tests
          Write-Host "filter: $filter"
          Write-Host "count: $($tests.Length)"
    - when:
        condition: "<<parameters.code_coverage>>"
        steps:
        - run:
            name: Run tests (using dotCover)
            command: >-
              ~/.dotnet/tools/dotnet-dotcover test
              --no-restore
              --no-build
              -c Release
              -l "junit;FailureBodyFormat=Verbose;LogFilePath=/tmp/junit/{assembly}.xml"
              --filter "$(cat .test_filter.txt)"
              --dcDisableDefaultFilters
              --dcReportType=DetailedXML
              --dcFilters="+:Libplanet;+:Libplanet.*;-:Libplanet.Tests;-:Libplanet.*.Tests;-:Libplanet.*.UnitTests;-:Libplanet.Benchmarks;-:Libplanet.Explorer"
            no_output_timeout: 360s
            environment:
              LC_ALL: "<<parameters.locale>>"
              LANG: "<<parameters.locale>>"
              LANGUAGE: "<<parameters.locale>>"
        - store_test_results:
            path: /tmp/junit
        - codecov:
            file: dotCover.Output.xml
    - unless:
        condition: "<<parameters.code_coverage>>"
        steps:
        - run:
            name: Run tests
            command: >-
              dotnet test
              --no-restore
              --no-build
              --configuration Release
              -p:ParallelizeTestCollections=false
              -l "junit;FailureBodyFormat=Verbose;LogFilePath=/tmp/junit/{assembly}.xml"
              --filter "$(cat .test_filter.txt)"
              --verbosity detailed
            no_output_timeout: 1800s
            environment:
              LC_ALL: "<<parameters.locale>>"
              LANG: "<<parameters.locale>>"
              LANGUAGE: "<<parameters.locale>>"
        - store_test_results:
            path: /tmp/junit

  linux_netcore_test_base:
    parameters:
      test_filter:
        type: string
        default: ""
      locale:
        type: string
        default: en_US.UTF-8
      code_coverage:
        type: boolean
        default: true
    steps:
      - run:
          name: Install lib6c-dev (for RocksDBSharp)
          shell: bash
          command: apt update -y && apt install -y libc6-dev liblz4-dev zlib1g-dev libsnappy-dev libzstd-dev
      - netcore_test_base:
          test_filter: "<<parameters.test_filter>>"
          locale: "<<parameters.locale>>"
          code_coverage: "<<parameters.code_coverage>>"

  macos_netcore_test_base:
    parameters:
      test_list_path:
        type: string
        default: .tests.txt
      locale:
        type: string
        default: en_US.UTF-8
      code_coverage:
        type: boolean
        default: true
    steps:
    - ulimit: { n: 10240 }
    - restore_cache:
        keys:
        - v1-macos-dotnet-sdk-6.0
    - run:
        name: Export PATH & DOTNET_ROOT
        shell: bash
        command: |
          {
            echo export PATH="$HOME/.dotnet:$PATH"
            echo export DOTNET_ROOT="$HOME/.dotnet"
          } >> $BASH_ENV
    - run:
        name: Install .NET 6.0 SDK
        shell: bash
        command: |
          set -evx
          echo $PATH > /dev/stderr
          if ! command -v dotnet && [[ ! -f "$HOME/.dotnet/dotnet" ]]; then
            curl \
              -L \
              -o /tmp/dotnet-install.sh \
              https://dot.net/v1/dotnet-install.sh
            chmod +x /tmp/dotnet-install.sh
            /tmp/dotnet-install.sh \
              --verbose \
              --channel 6.0
          fi
          command -v dotnet
    - save_cache:
        key: v1-macos-dotnet-sdk-6.0
        paths:
        - ~/.dotnet/
    - netcore_test_base:
        test_list_path: "<<parameters.test_list_path>>"
        locale: "<<parameters.locale>>"
        code_coverage: "<<parameters.code_coverage>>"

jobs:
  linux-netcore-build:
    parameters:
      test_filter:
        type: string
        default: ""
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:6.0
    resource_class: medium
    working_directory: /mnt/ramdisk
    steps:
    - netcore_build_base:
        test_filter: "<<parameters.test_filter>>"

  linux-netcore-test-netmq:
    parameters:
      parallelism:
        type: integer
        default: 4
      test_filter:
        type: string
        default: ""
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      TRANSPORT_TYPE: netmq
    resource_class: medium
    working_directory: /mnt/ramdisk
    parallelism: <<parameters.parallelism>>
    steps:
      - linux_netcore_test_base:
          code_coverage: false
          test_filter: <<parameters.test_filter>>

  linux-netcore-test-ar-SA:
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:6.0
    resource_class: medium
    working_directory: /mnt/ramdisk
    parallelism: 4
    steps:
    - linux_netcore_test_base:
        locale: ar_SA.UTF-8
        code_coverage: false

  linux-netcore-test-fr-FR:
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:6.0
    resource_class: medium
    working_directory: /mnt/ramdisk
    parallelism: 4
    steps:
    - linux_netcore_test_base:
        locale: fr_FR.UTF-8
        code_coverage: false

  macos-netcore-test:
    parameters:
      parallelism:
        type: integer
        default: 4
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
    parallelism: <<parameters.parallelism>>
    steps:
    - macos_netcore_test_base: { code_coverage: false }

  windows-netcore-test:
    parameters:
      parallelism:
        type: integer
        default: 6
    executor:
      name: win/server-2022
      size: medium
    parallelism: <<parameters.parallelism>>
    steps:
    - netcore_test_base: { code_coverage: false }

workflows:
  # main:
  #   jobs:
  #   - linux-netcore-build:
  #       test_filter: "FullyQualifiedName!~Libplanet.Net.Tests & CircleCI!=Skip"
  #   - linux-netcore-test-netmq:
  #       requires: [linux-netcore-build]
  #   - linux-netcore-test-ar-SA:
  #       requires: [linux-netcore-build]
  #   - linux-netcore-test-fr-FR:
  #       requires: [linux-netcore-build]
  #   - windows-netcore-test:
  #       requires: [linux-netcore-build]
  net:
    jobs:
    - linux-netcore-build:
        name: linux-netcore-build-net
        test_filter: "FullyQualifiedName~Libplanet.Net.Tests"
    - linux-netcore-test-netmq:
        name: linux-netcore-test-netmq-net
        requires: [linux-netcore-build-net]
        parallelism: 1
    # - macos-netcore-test:
    #     name: macos-netcore-test-net
    #     requires: [linux-netcore-build-net]
    #     parallelism: 1
    - windows-netcore-test:
        name: windows-netcore-test-net
        requires: [linux-netcore-build-net]
        parallelism: 1
